spring.application.name=spotify-api-getting_album_cover

#spotify api
spotify.api.url=https://api.spotify.com/v1
spotify.client.id=5f7ff6f18d454275a70ef4f522617bdc
spotify.client.secret=61241ff52fd242bd99dcc8f403baa563
